### ISSUE TITLE
Diagnostics always empty.

### ISSUE THREAD

**Issue by bruno-medeiros** [TypeFox/languageserver-example#1]
So I was trying and exploring the example again. I noticed there seems to be a problem either with the example code itself, or the bundled language server: You only get empty diagnostics. The example seems to expect some error diagnostic from `changeEvent.setText("entity Person extends NonExisting { ");` but none happens, even if the example is modified so that the string above is the initial content of the document. That is, I only get this diagnostic:

```
PublishDiagnosticsParamsImpl [
  uri = "file:///D:/devel/MelnormeEclipse.git/plugin_tooling.lsp/testdata/myproject/Foo.domain"
  diagnostics = ArrayList ()
]
```

**Comment by svenefftinge** [comment]
I think that is due to a bug we had on windows.

Am Montag, 25. Juli 2016 schrieb Bruno Medeiros :

**Comment by spoenemann** [comment]
If this is still an issue it should be reported to https://github.com/TypeFox/lsp4j-example
